import type { SiteData } from './types'

export interface User {
  id: string
  name: string
  initials: string
  jobTitle: string
  avatarBg: string
  avatarText: string
}

export const USERS: User[] = [
  { id: 'u1',  name: 'Grace Harris',      initials: 'GH', jobTitle: 'CNA',                    avatarBg: '#FEF3C7', avatarText: '#D97706' },
  { id: 'u2',  name: 'Ethan Foster',      initials: 'EF', jobTitle: 'NP',                     avatarBg: '#FCE7F3', avatarText: '#DB2777' },
  { id: 'u3',  name: 'Carla Diaz',        initials: 'CD', jobTitle: 'RN',                     avatarBg: '#FEE2E2', avatarText: '#DC2626' },
  { id: 'u4',  name: 'Andres Bohorquez',  initials: 'AB', jobTitle: 'LPN',                    avatarBg: '#EDE9FE', avatarText: '#7C3AED' },
  { id: 'u5',  name: 'Maya Thompson',     initials: 'MT', jobTitle: 'HR Manager',              avatarBg: '#DBEAFE', avatarText: '#2563EB' },
  { id: 'u6',  name: 'James Okafor',      initials: 'JO', jobTitle: 'UX Designer',             avatarBg: '#D1FAE5', avatarText: '#059669' },
  { id: 'u7',  name: 'Sofia Reyes',       initials: 'SR', jobTitle: 'Data Scientist',          avatarBg: '#FEF3C7', avatarText: '#D97706' },
  { id: 'u8',  name: 'Liam Chen',         initials: 'LC', jobTitle: 'DevOps Specialist',       avatarBg: '#FCE7F3', avatarText: '#DB2777' },
  { id: 'u9',  name: 'Priya Nair',        initials: 'PN', jobTitle: 'Product Manager',         avatarBg: '#EDE9FE', avatarText: '#7C3AED' },
  { id: 'u10', name: 'Daniel Wright',     initials: 'DW', jobTitle: 'Unit Secretary',          avatarBg: '#DBEAFE', avatarText: '#2563EB' },
  { id: 'u11', name: 'Aisha Kamara',      initials: 'AK', jobTitle: 'Operations Manager',      avatarBg: '#D1FAE5', avatarText: '#059669' },
  { id: 'u12', name: 'Marcus Bell',       initials: 'MB', jobTitle: 'Software Engineer',       avatarBg: '#FEE2E2', avatarText: '#DC2626' },
  { id: 'u13', name: 'Elena Petrov',      initials: 'EP', jobTitle: 'Financial Analyst',       avatarBg: '#FEF3C7', avatarText: '#D97706' },
  { id: 'u14', name: 'Noah Williams',     initials: 'NW', jobTitle: 'QA Engineer',             avatarBg: '#FCE7F3', avatarText: '#DB2777' },
  { id: 'u15', name: 'Fatima Al-Hassan',  initials: 'FA', jobTitle: 'Compliance Officer',      avatarBg: '#EDE9FE', avatarText: '#7C3AED' },
]

export const JOB_TITLES: string[] = [
  'CNA',
  'LPN',
  'RN',
  'BSN',
  'CRNA',
  'NP',
  'PA',
  'MD',
  'DO',
  'Unit Secretary',
  'HR Manager',
  'HR Coordinator',
  'HR Generalist',
  'UX Designer',
  'UI Designer',
  'Product Manager',
  'Product Designer',
  'Data Scientist',
  'Data Analyst',
  'Data Engineer',
  'DevOps Specialist',
  'DevOps Engineer',
  'Software Engineer',
  'Senior Software Engineer',
  'Staff Engineer',
  'Engineering Manager',
  'Junior Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'QA Engineer',
  'Security Engineer',
  'Site Reliability Engineer',
  'Business Analyst',
  'Systems Analyst',
  'Operations Manager',
  'Operations Coordinator',
  'Account Manager',
  'Account Executive',
  'Sales Representative',
  'Sales Manager',
  'Customer Success Manager',
  'Customer Support Specialist',
  'Financial Analyst',
  'Accountant',
  'Controller',
  'CFO',
  'CTO',
  'COO',
  'CEO',
  'Project Manager',
  'Program Manager',
  'Marketing Manager',
  'Marketing Coordinator',
  'Content Strategist',
  'Social Media Manager',
  'Facilities Manager',
  'Administrative Assistant',
  'Executive Assistant',
  'Receptionist',
  'Office Manager',
  'Legal Counsel',
  'Compliance Officer',
  'Risk Analyst',
  'Procurement Specialist',
  'Supply Chain Manager',
  'Logistics Coordinator',
]

const SUNNYVALE_SCOPES = [
  'CNA',
  'LPN',
  'RN',
  'BSN',
  'NP',
  'PA',
  'Unit Secretary',
  'HR Manager',
  'HR Coordinator',
  'HR Generalist',
  'UX Designer',
  'UI Designer',
  'Product Manager',
  'Product Designer',
  'Data Scientist',
  'Data Analyst',
  'DevOps Specialist',
  'DevOps Engineer',
  'Software Engineer',
  'Senior Software Engineer',
  'Junior Engineer',
  'QA Engineer',
  'Business Analyst',
  'Operations Manager',
  'Operations Coordinator',
  'Account Manager',
  'Customer Success Manager',
  'Financial Analyst',
  'Project Manager',
  'Compliance Officer',
  'Facilities Manager',
  'Administrative Assistant',
]

const MONMOUTH_SCOPES = ['Project Manager', 'Operations Manager', 'Account Manager', 'Sales Manager']

const HEALTHCARE_SCOPES = ['CNA', 'LPN', 'RN', 'NP', 'Unit Secretary', 'HR Manager']

export const SITES_DATA: SiteData[] = [
  {
    site: { id: 'sunnyvale', name: 'Sunnyvale Care', isPrimary: true },
    permissions: {
      siteId: 'sunnyvale',
      onboard: {
        canPerform: true,
        performScopes: SUNNYVALE_SCOPES,
        canApprove: true,
        approveScopes: SUNNYVALE_SCOPES,
      },
      edit: {
        canPerform: false,
        performScopes: [],
        canApprove: true,
        approveScopes: SUNNYVALE_SCOPES,
      },
      offboard: {
        canPerform: false,
        performScopes: [],
        canApprove: true,
        approveScopes: SUNNYVALE_SCOPES,
      },
    },
    tree: [
      { id: 'corp-hq', name: 'Corporate HQ', relation: 'parent' },
      { id: 'sunnyvale', name: 'Sunnyvale Care', relation: 'self' },
      { id: 'evergreen', name: 'Evergreen Center', relation: 'child-in-reach' },
      { id: 'harmony', name: 'Harmony Falls', relation: 'child-in-reach' },
      { id: 'clearwater', name: 'Clearwater Facility', relation: 'child-in-reach' },
      { id: 'oakhaven', name: 'Oakhaven Clinic', relation: 'child-approve-only' },
      { id: 'ponderosa', name: 'Ponderosa House', relation: 'child-approve-only' },
    ],
  },
  {
    site: { id: 'monmouth', name: 'Monmouth Builders', isPrimary: false },
    permissions: {
      siteId: 'monmouth',
      onboard: {
        canPerform: true,
        performScopes: MONMOUTH_SCOPES,
        canApprove: false,
        approveScopes: [],
      },
      edit: {
        canPerform: true,
        performScopes: ['Operations Manager', 'Account Manager'],
        canApprove: true,
        approveScopes: MONMOUTH_SCOPES,
      },
      offboard: {
        canPerform: false,
        performScopes: [],
        canApprove: false,
        approveScopes: [],
      },
    },
    tree: [
      { id: 'regional-east', name: 'Regional East HQ', relation: 'parent' },
      { id: 'monmouth', name: 'Monmouth Builders', relation: 'self' },
      { id: 'trenton-office', name: 'Trenton Office', relation: 'child-in-reach' },
      { id: 'camden-branch', name: 'Camden Branch', relation: 'child-approve-only' },
    ],
  },
  {
    site: { id: 'healthcare', name: 'Healthcare Solutions', isPrimary: false },
    permissions: {
      siteId: 'healthcare',
      onboard: {
        canPerform: false,
        performScopes: [],
        canApprove: true,
        approveScopes: HEALTHCARE_SCOPES,
      },
      edit: {
        canPerform: false,
        performScopes: [],
        canApprove: true,
        approveScopes: ['CNA', 'LPN'],
      },
      offboard: {
        canPerform: false,
        performScopes: [],
        canApprove: false,
        approveScopes: [],
      },
    },
    tree: [
      { id: 'national-hq', name: 'National HQ', relation: 'parent' },
      { id: 'healthcare', name: 'Healthcare Solutions', relation: 'self' },
      { id: 'metro-clinic', name: 'Metro Clinic', relation: 'child-in-reach' },
      { id: 'westside-med', name: 'Westside Medical', relation: 'child-out-of-scope' },
    ],
  },
]
